- name: Add the docker signing key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: Add the docker apt repo
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable' state=present

- name: Install packages
  apt:
    name: "{{ PACKAGES }}"
    state: present
    update_cache: true
    force: yes

- name: Add "{{ansible_user}}" user to "docker" group
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes
